# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Algoan PubSub Publish Workflow

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{runner.os}}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ matrix.node-version }}
    - run: npm ci
    - name: Wait on tests
      uses: lewagon/wait-on-check-action@v0.2
      with:
        ref: master
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        check-name: test (14.x)
        wait-interval: 20 # seconds
        allowed-conclusions: success
    - name: Run Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT_SEMANTIC_RELEASE }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
